#!/bin/bash -e

case "$1" in
    -h|--help)
        echo "Usage: [-f] <pod-id>"
        exit 0;;
    -f)
        follow="-f "
        shift;;
esac

pod="$1"
description="$(kubectl describe pod $pod)"
container=$(echo "$description" |awk '/Container ID:/{split($3,id,"/");print id[3]}')
node=$(echo "$description" |awk '/Node:/{print$2}')

hostfile="$HOME/.vcac-hosts"
if [ ! -f $hostfile ]; then hostfile="/etc/vcac-hosts"; fi
if [ -f $hostfile ]; then
    node_ip=$(echo $node | awk '{split($1,ip,"/");print ip[2]}')
    while IFS=' ' read -r -a line < $hostfile; do
        if [ "$node" = "${line[0]}" ]; then
            ssh ${line[1]} "ssh root@$node_ip \"docker logs $follow$container\""
            exit 0
        fi
    done
fi
echo "Unknown node $node"
exit -1

